### ISSUE TITLE
Change Apple Calendar support link

### ISSUE THREAD

**Issue by HandyHat** [BurntNail/knot#144]
It might make sense to change the Apple Calendar support link as it currently refers to an out-of-date version of MacOS.

MacOS link: https://support.apple.com/en-gb/guide/calendar/icl1022/mac
iOS link: https://support.apple.com/en-gb/guide/iphone/iph3d1110d4/16.0/ios/16.0

**Comment by BurntNail** [comment]
lol this went for so long that iOS updated. Thanks for the fix @HandyHat 

finished in 74f4468

**Comment by HandyHat** [comment]
> lol this went for so long that iOS updated

FYI https://support.apple.com/en-gb/guide/iphone/iph3d1110d4/ios will always point to the latest version of iOS if that helps @BurntNail
